name: Cluster RDP Smart Test

on:
  workflow_dispatch:

jobs:
  smart-cluster:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        shell: pwsh
        run: |
          Get-ChildItem ./scripts/*.sh | ForEach-Object { $_.IsReadOnly = $false }

      - name: Create VMs sequentially
        shell: pwsh
        run: |
          $SEQ_DELAYS = @(0, 900, 1800)
          $CLUSTER_SIZE = 3
          for ($i=1; $i -le $CLUSTER_SIZE; $i++) {
            Write-Host "⏱ Creating VM$i after $($SEQ_DELAYS[$i-1]) seconds..."
            Start-Sleep -Seconds $SEQ_DELAYS[$i-1]
            ./scripts/create_rdp_vm_smart.sh $i
            Write-Host "✅ VM$i created."
          }

      - name: Start Cluster Monitor
        shell: pwsh
        run: ./scripts/monitor_cluster_smart.sh
