name: Cluster RDP Smart Test

on:
  workflow_dispatch:

jobs:
  smart-cluster:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh

      - name: Create VMs sequentially
        run: |
          SEQ_DELAYS=(0 900 1800)  # 0s, 15min, 30min
          CLUSTER_SIZE=3
          for i in $(seq 1 $CLUSTER_SIZE); do
            echo "⏱ Creating VM$i after ${SEQ_DELAYS[$((i-1))]} seconds..."
            sleep ${SEQ_DELAYS[$((i-1))]}
            ./scripts/create_rdp_vm_smart.sh $i
            echo "✅ VM$i created."
          done

      - name: Start Cluster Monitor
        run: ./scripts/monitor_cluster_smart.sh
